import Head from 'next/head';
import axios from 'axios';
import Header from '../Common/Header';
import { useState } from 'react';
import { useEffect } from 'react';
import { useRouter } from 'next/router';

const mydata = () => {
    const [sildeData, setSildeData] = useState([]);
    const [loading, setLoading] = useState(true);
    const router = useRouter();
    const { pro_id } = router.query;
    useEffect(() => {
        axios.get(`http://127.0.0.1:8000/api/onedataview/${pro_id}`)
            .then(function (response) {
                console.log(response);
                setSildeData(response.data.Products);
                setLoading(false);
            })
            .catch(function (error) {
                console.log(error);
            })
    }, [pro_id])
    if (loading) {
        return (
            <h3>Loading...</h3>
        )
    }
    else {
        return (
            <>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"></link>
                    <link rel="stylesheet" href="//use.fontawesome.com/releases/v5.0.7/css/all.css"></link>
                    <link href='../assest/style.css' rel='stylesheet' />
                </Head>
                <main>
                    < Header />
                    <div className='container'>
                        <div className='row'>
                            <div className='col-md-8 offset-md-2 proDelatis mb-3'>
                                <div class="card mt-4">
                                    <h5 class="card-header">Product Details</h5>
                                    <img src={`http://127.0.0.1:8000/${sildeData.image}`} class="card-img-top" alt="jamil" style={{ width: `100%`, height: `400px` }} />
                                    <div class="card-body">

                                        <h5 class="card-title mt-2" style={{ color: `#355197` }}>{sildeData.pro_name}</h5>
                                        <h6 class="card-title">{sildeData.price}</h6>
                                        <p class="card-text">{sildeData.pro_details}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </>
        )
    }

}

export default mydata