import Head from 'next/head';
import axios from 'axios';
import Header from './Common/Header';
import { useState } from 'react';
import { useEffect } from 'react';

const Allproview = () => {
    const [sildeData, setSildeData] = useState([]);
    const [loading, setLoading] = useState(true);
    useEffect(() => {
        axios.get('http://127.0.0.1:8000/api/UserProduct')
            .then(function (response) {
                console.log(response);
                setSildeData(response.data.Products);
                setLoading(false);
            })
            .catch(function (error) {
                console.log(error);
            })
    }, [])
    if (loading) {
        return (
            <h3>Loading...</h3>
        )
    } else {
        return (

            <>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"></link>
                    <link rel="stylesheet" href="//use.fontawesome.com/releases/v5.0.7/css/all.css"></link>
                    <link href='../assest/style.css' rel='stylesheet' />
                </Head>
                <Header />
                <div className='container-fluid mt-5'>
                    <div className='row'>
                        {
                            sildeData.map((items) => {
                                return (
                                    <div className='col-md-3 mb-5'>
                                        <div class="card" style={{ width: `18rem` }} >
                                            <div class="card-body">
                                                <img src={`http://127.0.0.1:8000/${items.image}`} class="card-img-top" alt="jamil" style={{ width: `254px`, height: `177px` }} />
                                                <h5 class="card-title mt-2" style={{ color: `#355197` }}>{items.pro_name}</h5>
                                                <h6 class="card-title">{items.price}</h6>
                                                <p class="card-text">{items.pro_details}</p>
                                                <button href="#" class="card_button">View Details</button>
                                            </div>
                                        </div>
                                    </div>
                                )
                            })
                        }

                    </div>
                </div>
            </>
        )
    }

}

export default Allproview