import Head from 'next/head';
import Document, { body } from 'next/document';
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import Carousel from 'react-multi-carousel';
import 'react-multi-carousel/lib/styles.css';
import axios from 'axios';
import Header from './Common/Header';
import { useState } from 'react';
import { useEffect } from 'react';
import Link from 'next/link';


export default function Home() {
  const [catdata, setCatdata] = useState([]);
  const [sildeData, setSildeData] = useState([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    axios.get('http://127.0.0.1:8000/api/uersCatViewlimit')
      .then(function (response) {
        console.log(response);
        setCatdata(response.data.Categroy);
        setLoading(false);
      })
      .catch(function (error) {
        console.log(error);
      })
  }, [])
  useEffect(() => {
    axios.get('http://127.0.0.1:8000/api/UserProduct')
      .then(function (response) {
        console.log(response);
        setSildeData(response.data.Products);
        setLoading(false);
      })
      .catch(function (error) {
        console.log(error);
      })
  }, [])
  const responsive = {
    desktop: {
      breakpoint: { max: 3000, min: 1024 },
      items: 3,
      slidesToSlide: 3 // optional, default to 1.
    },
    tablet: {
      breakpoint: { max: 1024, min: 464 },
      items: 2,
      slidesToSlide: 2 // optional, default to 1.
    },
    mobile: {
      breakpoint: { max: 464, min: 0 },
      items: 1,
      slidesToSlide: 1 // optional, default to 1.
    }
  };

  if (loading) {
    return (
      <h3>Loading...</h3>
    )
  } else {
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"></link>
          <link rel="stylesheet" href="//use.fontawesome.com/releases/v5.0.7/css/all.css"></link>
          <link href='../assest/style.css' rel='stylesheet' />
        </Head>
        <body>
          <main>
            < Header />
            <div className='container'>
              <div className='row'>
                <div className='col-md-4 varius_down'>
                  <div className='varius_mobile'>
                    <h4>Varius porttitor</h4>
                    <h4 style={{ color: `#355197` }}>imperdiet.</h4>
                    <p>Making protection,smart and secuare</p>
                    <button type="button" class="btn btn-primary">Get Started</button>
                  </div>
                </div>
                <div className='col-md-8 mt-5'>
                  <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-indicators">
                      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="buttomColor bg-primary active" aria-current="true" aria-label="Slide 1"></button>
                      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" class="buttomColor" aria-label="Slide 2"></button>
                      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" class="buttomColor" aria-label="Slide 3"></button>
                    </div>
                    <div class="carousel-inner">
                      <div class="carousel-item active">
                        <div className='row'>
                          <div className='col-md-6'>
                            <img src="../assest/8.jpg" class="d-block w-100" alt="hello" />
                          </div>
                          <div className='col-md-6 sileder_size' >
                            <div className='container'>
                              <div className='row'>
                                <div className='col-md-2'>
                                  <span><img src='../assest/7.png' style={{ width: `30px`, height: `30px` }} /></span>
                                </div>
                                <div className='col-md-10'>
                                  <span><h4>Flexible insurance with</h4></span>
                                  <span><h4>affordable price</h4></span>
                                </div>
                              </div>
                            </div>
                            <div className='container'>
                              <div className='row'>
                                <div className='col-md-2'>
                                  <span><img src='../assest/7.png' style={{ width: `30px`, height: `30px` }} /></span>
                                </div>
                                <div className='col-md-10'>
                                  <span><h4>Flexible insurance with</h4></span>
                                  <span><h4>affordable price</h4></span>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="carousel-item">
                        <div className='row'>
                          <div className='col-md-6'>
                            <img src="../assest/8.jpg" class="d-block w-100" alt="hello" />
                          </div>
                          <div className='col-md-6 sileder_size'>
                            <div className='container'>
                              <div className='row'>
                                <div className='col-md-2'>
                                  <span><img src='../assest/7.png' style={{ width: `30px`, height: `30px` }} /></span>
                                </div>
                                <div className='col-md-10'>
                                  <span><h4>Flexible insurance with</h4></span>
                                  <span><h4>affordable price</h4></span>
                                </div>
                              </div>
                            </div>
                            <div className='container'>
                              <div className='row'>
                                <div className='col-md-2'>
                                  <span><img src='../assest/7.png' style={{ width: `30px`, height: `30px` }} /></span>
                                </div>
                                <div className='col-md-10'>
                                  <span><h4>Flexible insurance with</h4></span>
                                  <span><h4>affordable price</h4></span>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="carousel-item">
                        <div className='row'>
                          <div className='col-md-6'>
                            <img src="../assest/8.jpg" class="d-block w-100" alt="hello" />
                          </div>
                          <div className='col-md-6 sileder_size' >
                            <div className='container'>
                              <div className='row'>
                                <div className='col-md-2'>
                                  <span><img src='../assest/7.png' style={{ width: `30px`, height: `30px` }} /></span>
                                </div>
                                <div className='col-md-10'>
                                  <span><h4>Flexible insurance with</h4></span>
                                  <span><h4>affordable price</h4></span>
                                </div>
                              </div>
                            </div>
                            <div className='container'>
                              <div className='row'>
                                <div className='col-md-2'>
                                  <span><img src='../assest/7.png' style={{ width: `30px`, height: `30px` }} /></span>
                                </div>
                                <div className='col-md-10'>
                                  <span><h4>Flexible insurance with</h4></span>
                                  <span><h4>affordable price</h4></span>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className='container'>
              <div className='row'>
                <h3 className='addcart_head mt-5'>
                  Making protection,smart and secuare
                </h3>
              </div>
            </div>
            <div className='container addcart mt-5 mb-5'>
              <div className='row'>
                {
                  catdata.map((items) => {
                    return (
                      <div class="col-md-2">
                        <div class="card4">
                          <div class="card-1">
                            <img src={`http://127.0.0.1:8000/${items.image}`} style={{ width: `50px`, height: `50px` }} />
                            <h1><Link href={`/Common/${items.id}`}>{items.categroy_name}</Link></h1>
                          </div>
                        </div>
                      </div>
                    )

                  })
                }
                <div class="col-md-2">
                  <div class="card4 ">
                    <div class="card-2">
                      <img src='../assest/12.png' style={{ width: `50px`, height: `50px` }} />
                      <span><Link href={`/Allproview`}><a><h2>All view</h2></a></Link></span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className='container mb-5'>
              <div className='row'>
                <h3 className='addcart_head mt-5'>
                  Lorem Ipsum is simply dummy text of the printing and typesetting.
                </h3>
              </div>
            </div>
            <div className='container mb-5'>
              <div className='row'>
                <Carousel
                  responsive={responsive}
                  swipeable={false}
                  draggable={false}
                  ssr={true} // means to render carousel on server-side.
                  infinite={true}
                >
                  {
                    sildeData.map((items) => {
                      return (
                        <div className='col-md-4'>
                          <div class="card" style={{ width: `18rem` }} >

                            <div class="card-body">
                              <img src={`http://127.0.0.1:8000/${items.image}`} class="card-img-top" alt="jamil" style={{ width: `254px`, height: `177px` }} />
                              <h5 class="card-title mt-2" style={{ color: `#355197` }}>{items.pro_name}</h5>
                              <h6 class="card-title">{items.price}</h6>
                              <p class="card-text">{items.pro_details}</p>
                              <button href="#" class="card_button"><Link href={`/product/${items.id}`}><a style={{color:`#fff`,textDecoration:`none`}}>View Details</a></Link></button>
                            </div>
                          </div>
                        </div>
                      )
                    })
                  }
                </Carousel>
              </div>
            </div>
          </main>
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" />
        </body>
      </div>
    )
  }
}
